---
#Available Languages:
# en - English
# ru - Russian
# fr - French
# de - German
Language: en

#Min. and Max. lenght of Faction name.
min-length: 3
max-length: 8

#Allow faction members can attack other members.
friendly-attack: false

#Set Faction NameTag.
faction-nametag: false
...